### ISSUE TITLE
Supported rails versions

### ISSUE THREAD

**Issue by ojab** [watir/watir-rails#28]
I d tried to debug something and tried to rewrite some stuff in `Watir::Rails` and found out that rails-2.x still supported, so I tried to actually check if it works.

Long story short: Rails-2.3.18 cannot run on ruby >= 2.2 since it uses `Config::CONFIG` which is 
```
irb(main):001:0> Config
(irb):1:in `irb_binding': Use RbConfig instead of obsolete and deprecated Config.
=> RbConfig::Obsolete
```
on ruby-2.1.10 and dropped in ruby-2.2.

On ruby-2.1.10 we have another issue: rubygems doesn't work:
```
gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/latest_specs.4.8.gz)
```
It was compiled with `openssl-1.0.2u` and ruby-2.2 with the same version works fine, I assume that ruby-2.1 openssl module lacks current ciphers.

So the question is: can Rails-2.x be dropped in order to simplify some stuff? Same question goes for rails-3, but I haven't tried to boot it yet.

**Comment by jarmo** [comment]
I'm not sure, but I would think that Rails 2.x is used with even older Ruby versions nowadays.

However, I'm not against of removing Rails 2.x and 3.x support since it's pretty sure that there will not be any updates in this library which would be targeted towards these versions. If anyone would like to use `watir-rails` with Rails 2.x or 3.x then they can use older version of this gem and use it as it has been for the last x years.

So yeah, go ahead and remove support for these if you have anything new to add, which would make it more difficult if 2.x and 3.x needs to be supported.

I appreciate that you asked in advance!

Closing this issue now and send a separate PR if with removing support from these versions.
